version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11
  
jobs:
  test_scraper:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest

  deploy_frontend:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "src/bandcamp_merch_availability/frontend/package.json" }}
            - v1-dependencies-
      - run:
          name: Install, test, and build frontend
          command: |
            cd src/bandcamp_merch_availability/frontend
            npm install
            npm run test
            npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "src/bandcamp_merch_availability/frontend/package.json" }}
          paths:
            - src/bandcamp_merch_availability/frontend/node_modules

      # deploy frontend
      - aws-s3/sync:
          from: src/bandcamp_merch_availability/frontend/build
          to: 's3://bandcamp-merch-availability'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read
          overwrite: false


  scrape_and_deploy_data:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run scraper and deploy results
          command: |
            . venv/bin/activate
            cd src/bandcamp_merch_availability
            rm -f bandcamp_merch.json
            scrapy crawl bandcamp_merch -o bandcamp_merch.json
            cat bandcamp_merch.json
      # Deploy scraped data
      - aws-s3/copy:
          from: src/bandcamp_merch_availability/bandcamp_merch.json
          to: 's3://bandcamp-merch-availability'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read


workflows:
  version: 2

  deploy_app:
    jobs:
      - test_scraper:
          filters:
            branches:
              only: master
      - deploy_frontend:
          filters:
            branches:
              only: master
          requires:
            - test_scraper

  scrape_and_deploy_data:
    # triggers:
    #   - schedule:
    #       cron: "0 6 * * *"
    #       filters:
    #         branches:
    #           only:
    #             - master
    jobs:
      - scrape_and_deploy_data
